### ISSUE TITLE
Error after update to 0.1.4 version

### ISSUE THREAD

**Issue by ShmuelRonen** [nimadez/mental-diffusion#5]
----------------------------------------
 Mental Diffusion 0.1.4 - 2023 @nimadez
 Torch:         2.0.1+cu118
 Diffusers:     0.17.1
 Device:        CUDA
 Network:       OFFLINE
 Checkpoints:   10
 Custom VAE:    True
----------------------------------------
09:26:21.909 INFO Main loading checkpoint [deliberate_v2] ...
Traceback (most recent call last):
  File "P:\mental-diffusion\mental-diffusion\src\main.py", line 50, in <module>
    md.init()
  File "P:\mental-diffusion\mental-diffusion\src\md.py", line 126, in init
    load_checkpoint(ctx.checkpoint_name)
  File "P:\mental-diffusion\mental-diffusion\src\md.py", line 174, in load_checkpoint
    ctx.pipe = utils.StableDiffusionPipeline_from_ckpt(
  File "P:\mental-diffusion\mental-diffusion\src\utils.py", line 143, in StableDiffusionPipeline_from_ckpt
    pipe = download_from_original_stable_diffusion_ckpt(
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'text_encoder'
Press any key to continue . . .

**Comment by ShmuelRonen** [comment]
I installd everything from beginning and now it's OK

**Comment by nimadez** [comment]
Diffusers updated to 0.18.0
If there is such an error, rest assured that I have made major changes to the Python code.
Of course, since we are in alpha phase, there may be many changes, all of which are just to improve performance and stability.

**Comment by nimadez** [comment]
Diffusers updated to 0.18.0
If there is such an error, rest assured that I have made major changes to the Python code.
Of course, since we are in alpha phase, there may be many changes, all of which are just to improve performance and stability.

**Comment by ShmuelRonen** [comment]
Thanks for your work!!!
